title: "awesome-bof"

# activate the theme
theme: "just-the-docs"

# start in dark mode
color_scheme: "dark"

# enable instant search box (optional)
search_enabled: true

# link back to the repo (optional)
aux_links:
  "GitHub Repo": "https://github.com/chryzsh/awesome-bof"
