title: awesome-bof

remote_theme: just-the-docs/just-the-docs   # ← replaces `theme:`

color_scheme: dark

url: "https://chryzsh.github.io"

baseurl: "/awesome-bof"

plugins:            # make sure the plugin is on
  - jekyll-remote-theme

